version: '3'
services:
  db:
    image: mongo
    restart: always
    volumes:
      - db:/data/db

  app:
    build: ./dist
    restart: always
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - NODE_PORT=3000
      - MONGO_URI=mongodb://db/demo

volumes:
  db:
